export type TKind =
    | "bambooOne"
    | "bambooTwo"
    | "bambooThree"
    | "bambooFour"
    | "bambooFive"
    | "bambooSix"
    | "bambooSeven"
    | "bambooEight"
    | "bambooNine"
    | "circleOne"
    | "circleTwo"
    | "circleThree"
    | "circleFour"
    | "circleFive"
    | "circleSix"
    | "circleSeven"
    | "circleEight"
    | "circleNine"
    | "characterOne"
    | "characterTwo"
    | "characterThree"
    | "characterFour"
    | "characterFive"
    | "characterSix"
    | "characterSeven"
    | "characterEight"
    | "characterNine"
    | "dragonRed"
    | "dragonGreen"
    | "dragonWhite"
    | "windEast"
    | "windSouth"
    | "windWest"
    | "windNorth"
    | "blank";

export type TOrientation = "bottom" | "left" | "right" | "top";
