export const reverseChildIndex = {
  '& > div:nth-child(1)': { zIndex: 17 },
  '& > div:nth-child(2)': { zIndex: 16 },
  '& > div:nth-child(3)': { zIndex: 15 },
  '& > div:nth-child(4)': { zIndex: 14 },
  '& > div:nth-child(5)': { zIndex: 13 },
  '& > div:nth-child(6)': { zIndex: 12 },
  '& > div:nth-child(7)': { zIndex: 11 },
  '& > div:nth-child(8)': { zIndex: 10 },
  '& > div:nth-child(9)': { zIndex: 9 },
  '& > div:nth-child(10)': { zIndex: 8 },
  '& > div:nth-child(11)': { zIndex: 7 },
  '& > div:nth-child(12)': { zIndex: 6 },
  '& > div:nth-child(13)': { zIndex: 5 },
  '& > div:nth-child(14)': { zIndex: 4 },
  '& > div:nth-child(15)': { zIndex: 3 },
  '& > div:nth-child(16)': { zIndex: 2 },
  '& > div:nth-child(17)': { zIndex: 1 },
};

